# Generated by Django 5.0.1 on 2024-01-27 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
            ],
            options={
                'verbose_name': 'направление',
                'verbose_name_plural': 'направления',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='имя')),
                ('phone', models.CharField(max_length=25, verbose_name='телефон')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='почта')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.area', verbose_name='направление')),
            ],
            options={
                'verbose_name': 'команда',
                'verbose_name_plural': 'команды',
            },
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('address', models.CharField(max_length=50, verbose_name='адрес')),
                ('phone', models.CharField(max_length=25, verbose_name='номер')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='почта')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.area', verbose_name='Направление')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'клиника',
                'verbose_name_plural': 'клиники',
            },
        ),
    ]
